---
abstract: 'send warnings with ಠ_ಠ'
author:
  - 'Karen Etheridge <ether@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Pod::Wordlist::hanekomu: 0
  Test::CPAN::Meta: 0
  Test::CheckDeps: 0.002
  Test::EOL: 0
  Test::More: 0.94
  Test::NoTabs: 0
  Test::Pod: 1.41
  Test::Spelling: 0.12
  Test::Warnings: 0.005
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-LookOfDisapproval
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  utf8: 0
version: 0.003
